/*
SQLyog 企业版 - MySQL GUI v8.14 
MySQL - 5.7.11-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

UPDATE `sys_menu` SET  `MenuName`='申请', `ParentId`='154', `MenuType`='1', `AdminType`='2', `AppId`='2', `MenuUrl`='/debt/proclaims/payinvest/apply_list.do', `RelationUrl`='/debt/proissue/proinfo/view.do,/debt/proissue/profiles/view.do,/debt/proissue/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/debt/proclaims/payinvest/payfailedindex.do,/debt/proclaims/payinvest/payindex.do,/debt/proclaims/payinvest/planlist.do,/debt/proclaims/payinvest/plandetail.do,/debt/proclaims/payinvest/paylist.do,/debt/proclaims/payinvest/dopayfailed.do,/debt/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proclaims/payinvest/getPayInvestDetail.do', `Target`='1', `IsButton`='1', `ShowIndex`='0', `MenuImgUrl`=NULL, `UpdateOperatorId`='138', `CreateTime`='2015-09-07 09:17:15', `CreateOperatorId`='111', `UpdateTime`='2017-12-14 15:58:29', `IsValid`='1', `Remark`='' WHERE `Id`='163';
UPDATE `sys_menu` SET  `MenuName`='申请', `ParentId`='282', `MenuType`='1', `AdminType`='2', `AppId`='2', `MenuUrl`='/incomeright/proclaims/payinvest/apply_list.do', `RelationUrl`='/debt/proissue/proinfo/view.do,/debt/proissue/profiles/view.do,/debt/proissue/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/debt/proclaims/payinvest/payfailedindex.do,/debt/proclaims/payinvest/payindex.do,/debt/proclaims/payinvest/planlist.do,/debt/proclaims/payinvest/plandetail.do,/debt/proclaims/payinvest/paylist.do,/debt/proclaims/payinvest/dopayfailed.do,/debt/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proclaims/payinvest/getPayInvestDetail.do', `Target`='1', `IsButton`='1', `ShowIndex`='0', `MenuImgUrl`=NULL, `UpdateOperatorId`='138', `CreateTime`='2015-09-14 14:35:44', `CreateOperatorId`='138', `UpdateTime`='2017-12-14 15:58:42', `IsValid`='1', `Remark`='' WHERE `Id`='291';
UPDATE `sys_menu` SET  `MenuName`='查询', `ParentId`='154', `MenuType`='1', `AdminType`='2', `AppId`='2', `MenuUrl`='/debt/proclaims/payinvest/list.do', `RelationUrl`='/debt/proissue/proinfo/view.do,/debt/proissue/profiles/view.do,/debt/proissue/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/debt/proclaims/payinvest/payfailedindex.do,/debt/proclaims/payinvest/payindex.do,/debt/proclaims/payinvest/planlist.do,/debt/proclaims/payinvest/plandetail.do,/debt/proclaims/payinvest/paylist.do,/debt/proclaims/payinvest/dopayfailed.do,/debt/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/debt/proclaims/payinvest/applyhistory.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proclaims/payinvest/to_payinvest_list_export.do,/debt/proclaims/payinvest/export_payinvest_list.do,/debt/proclaims/payinvest/to_payinvest_list_export.do,/debt/proclaims/payinvest/export_payinvest_list.do,/debt/proclaims/payinvest/bizplandetails.do', `Target`='1', `IsButton`='1', `ShowIndex`='2', `MenuImgUrl`=NULL, `UpdateOperatorId`='138', `CreateTime`='2015-09-07 09:17:48', `CreateOperatorId`='111', `UpdateTime`='2017-12-13 10:19:21', `IsValid`='1', `Remark`='' WHERE `Id`='165';
UPDATE `sys_menu` SET  `MenuName`='查询', `ParentId`='282', `MenuType`='1', `AdminType`='2', `AppId`='2', `MenuUrl`='/incomeright/proclaims/payinvest/list.do', `RelationUrl`='/incomeright/proinfo/view.do,/incomeright/profiles/view.do,/incomeright/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/incomeright/proclaims/payinvest/payfailedindex.do,/incomeright/proclaims/payinvest/payindex.do,/incomeright/proclaims/payinvest/planlist.do,/incomeright/proclaims/payinvest/plandetail.do,/incomeright/proclaims/payinvest/paylist.do,/incomeright/proclaims/payinvest/dopayfailed.do,/incomeright/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/incomeright/proclaims/payinvest/applyhistory.do,/incomeright/proclaims/payinvest/to_payinvest_list_export.do,/incomeright/proclaims/payinvest/export_payinvest_list.do,/incomeright/proclaims/payinvest/to_payinvest_list_export.do,/incomeright/proclaims/payinvest/export_payinvest_list.do,/incomeright/proclaims/payinvest/bizplandetails.do', `Target`='1', `IsButton`='1', `ShowIndex`='2', `MenuImgUrl`=NULL, `UpdateOperatorId`='138', `CreateTime`='2015-09-14 14:37:55', `CreateOperatorId`='138', `UpdateTime`='2017-12-13 10:19:39', `IsValid`='1', `Remark`='' WHERE `Id`='293';

INSERT INTO `sys_menu` (`Id`, `MenuName`, `ParentId`, `MenuType`, `AdminType`, `AppId`, `MenuUrl`, `RelationUrl`, `Target`, `IsButton`, `ShowIndex`, `MenuImgUrl`, `UpdateOperatorId`, `CreateTime`, `CreateOperatorId`, `UpdateTime`, `IsValid`, `Remark`) VALUES('592','复核','154','1','2','2','/debt/proclaims/payinvest/audit_list.do','/debt/proissue/proinfo/view.do,/debt/proissue/profiles/view.do,/debt/proissue/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/debt/proclaims/payinvest/payfailedindex.do,/debt/proclaims/payinvest/payindex.do,/debt/proclaims/payinvest/planlist.do,/debt/proclaims/payinvest/plandetail.do,/debt/proclaims/payinvest/paylist.do,/debt/proclaims/payinvest/dopayfailed.do,/debt/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proclaims/payinvest/getPayInvestDetail.do','1','1','1',NULL,'138','2017-12-11 10:37:53','138','2017-12-13 10:19:15','1','');
INSERT INTO `sys_menu` (`Id`, `MenuName`, `ParentId`, `MenuType`, `AdminType`, `AppId`, `MenuUrl`, `RelationUrl`, `Target`, `IsButton`, `ShowIndex`, `MenuImgUrl`, `UpdateOperatorId`, `CreateTime`, `CreateOperatorId`, `UpdateTime`, `IsValid`, `Remark`) VALUES('593','复核','282','1','2','2','/incomeright/proclaims/payinvest/audit_list.do','/debt/proissue/proinfo/view.do,/debt/proissue/profiles/view.do,/debt/proissue/proinfo/feedlist.do,/user/view.do,/memberoperator/advisor-rz/to-advisor-admin-info.do,/user/feed.do,/debt/proclaims/payinvest/payfailedindex.do,/debt/proclaims/payinvest/payindex.do,/debt/proclaims/payinvest/planlist.do,/debt/proclaims/payinvest/plandetail.do,/debt/proclaims/payinvest/paylist.do,/debt/proclaims/payinvest/dopayfailed.do,/debt/proclaims/payinvest/dopay.do,/user/view/usertype.do,/user/view/linkinfo.do,/user/view/bankinfo.do,/user/view/files.do,/debt/proissue/profiles/viewapplication.do,/debt/proissue/profiles/downsealapply.do,/debt/proclaims/payinvest/getPayInvestDetail.do','1','1','1',NULL,'138','2017-12-11 10:46:39','138','2017-12-13 10:19:33','1','');





